### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by paduhq** [laontme/erbuc#1]
![Screenshot_20200716-210721](https://user-images.githubusercontent.com/63902328/87674325-6f106500-c7a8-11ea-8ea8-2164749eb6aa.png)

Maybe you can try use workers by cloudflare to setup serverless app?

**Comment by laontme** [comment]
@paduhq, а month ago, everything worked. In the evening I'll see what happened

**Comment by kaizoku75** [comment]
still not working

**Comment by laontme** [comment]
> still not working

@kaizoku75 @paduhq 
Fixed
